#!/usr/bin/env python3
"""
make_fixtures.py — deterministically generate the Oracle-Diff Gate references +
proof-bundle fixtures, then self-verify each against judge_kernel.py.

Every array is computed here with the SAME helpers the judge uses (gen_inputs,
canonical_hash, ULP), so the sealed hashes and dtype-derived tolerances line up by
construction. Honest hardware outputs are emulated in numpy (bf16 input rounding /
exact int accumulation); forgeries are surgical mutations. Run:

  python3 make_fixtures.py          # writes files + prints each fixture's verdict
"""

import copy
import hashlib
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import judge_kernel as jk  # noqa: E402

REFS = os.path.join(HERE, "references")
SHAPE = [16, 128, 128]          # [M, N, K]
TILE = [8, 128, 128]
GRID = [2, 1]                   # ceil(M/tm)=2, ceil(N/tn)=1
SRC = hashlib.sha256(b"tiled_gemm reference kernel v1").hexdigest()
BLOCK_SPEC = {
    "a": {"block": [8, 128], "index_map": "(i,j)->(i,0)"},
    "b": {"block": [128, 128], "index_map": "(i,j)->(0,j)"},
    "out": {"block": [8, 128], "index_map": "(i,j)->(i,j)"},
}


def to_bf16(x):
    """Round float32 to bf16 (round-to-nearest-even) by truncating the low 16
    mantissa bits — the honest reduced-precision path an MXU would take."""
    x = np.ascontiguousarray(x, dtype=np.float32)
    u = x.view(np.uint32)
    bias = ((u >> 16) & 1) + 0x7FFF
    return ((u + bias) & 0xFFFF0000).view(np.float32)


def honest_bf16_gemm(shape, seed):
    a, b = jk.gen_inputs(shape, seed, "bf16")            # float64 inputs
    out = to_bf16(a.astype(np.float32)) @ to_bf16(b.astype(np.float32))  # fp32 accumulate
    return np.asarray(out, dtype=np.float64)


def honest_int8_gemm(shape, seed):
    a, b = jk.gen_inputs(shape, seed, "int8")
    return (a @ b).astype(np.int64)


def sealed(arr):
    """Return (list, sha256) sealing an output array as it will sit in the bundle."""
    lst = arr.tolist()
    return lst, jk.canonical_hash(lst)


def base_bundle(problem_id, dtype, vis_arr, ho_arr, declared_tol=None):
    vis_list, vis_hash = sealed(vis_arr)
    ho_list, ho_hash = sealed(ho_arr)
    bundle = {
        "schema": jk.SCHEMA,
        "task": jk.TASK,
        "problem_id": problem_id,
        "constraints": {"shape": list(SHAPE), "tile": list(TILE),
                        "declared_dtype": dtype, "accum_dtype": "int32" if dtype in jk.INT_DTYPES else "fp32"},
        "kernel": {"name": f"tiled_gemm_{dtype}", "source_sha256": SRC, "grid": list(GRID), "block_spec": BLOCK_SPEC},
        "oracle": {"numeric": {"runner": "numpy.float64", "reduction_len": SHAPE[2]}},
        "hardware": {"device_kind": "TPU v5e", "output": vis_list, "output_sha256": vis_hash},
        "holdout_hardware": {"output": ho_list, "output_sha256": ho_hash},
        "claim": {},
        "meta": {"model": "opus-4.8", "note": "generated by make_fixtures.py; hardware output is numpy-emulated (roadmap, not on-silicon)"},
    }
    if declared_tol is not None:
        bundle["claim"]["declared_tolerance"] = declared_tol
    return bundle


def reseal(block):
    block["output_sha256"] = jk.canonical_hash(block["output"])


def write(name, obj):
    # bundles carry large float arrays — write them compact (the sealed hash is
    # computed over each array's own canonical JSON, independent of file layout).
    path = os.path.join(HERE, name)
    with open(path, "w") as f:
        json.dump(obj, f, separators=(",", ":"))
    return path


def write_ref(problem_id, dtype, vis_seed, ho_seed):
    ref = {"task": jk.TASK, "contract": "gemm", "shape": list(SHAPE),
           "declared_dtype": dtype, "accum_dtype": "int32" if dtype in jk.INT_DTYPES else "fp32",
           "inputs": {"seed": vis_seed}, "holdout": {"seed": ho_seed}}
    os.makedirs(REFS, exist_ok=True)
    with open(os.path.join(REFS, f"{problem_id}.json"), "w") as f:
        json.dump(ref, f, indent=2)


def main():
    # ---- references (hidden ground truth: only seeds + shape + dtype) ----
    write_ref("gemm_bf16_tile1", "bf16", 12345, 67890)
    write_ref("gemm_int8_tile1", "int8", 2468, 13579)

    fixtures = []  # (filename, expected_exit, note)

    # bf16 honest outputs on visible + held-out batches
    vis = honest_bf16_gemm(SHAPE, 12345)
    ho = honest_bf16_gemm(SHAPE, 67890)

    # derived bias bound, to place the DEGRADED forgery in the "passes max-abs,
    # fails the zero-mean check" regime (a small systematic offset).
    ref_vis = jk.reference_output(SHAPE, 12345, "bf16")
    delta = 3.0 * jk.BIAS_C * jk.ULP["bf16"] * float(np.abs(ref_vis).mean())

    # K9/K1/K3/K10/K11 — genuine end-to-end ACCEPT
    write("bundle-gemm-bf16-OK.json", base_bundle("gemm_bf16_tile1", "bf16", vis, ho))
    fixtures.append(("bundle-gemm-bf16-OK.json", 0, "genuine bf16 kernel"))

    # K2 — mis-tiled kernel -> STRUCTURE (exit 3)
    b = base_bundle("gemm_bf16_tile1", "bf16", vis, ho)
    b["constraints"]["tile"] = [8, 100, 128]   # 100 not divisible by 128 and != N
    write("bundle-gemm-bf16-MISTILE.json", b)
    fixtures.append(("bundle-gemm-bf16-MISTILE.json", 3, "output block cols violate the (8,128) MXU rule"))

    # K4 — claimant-chosen (loose) tolerance -> REPRODUCIBILITY (exit 4)
    rtol, _ = jk.derive_tolerance("bf16", SHAPE[2], float(np.abs(ref_vis).max()))
    b = base_bundle("gemm_bf16_tile1", "bf16", vis, ho, declared_tol=round(rtol * 5.0, 6))
    write("bundle-gemm-bf16-LOOSETOL.json", b)
    fixtures.append(("bundle-gemm-bf16-LOOSETOL.json", 4, "declared tolerance disagrees with the dtype-derived one"))

    # K5 — sealed-hash mismatch (array swapped, stale hash) -> REPRODUCIBILITY (exit 4)
    b = base_bundle("gemm_bf16_tile1", "bf16", vis, ho)
    ok_hash = b["hardware"]["output_sha256"]
    b["hardware"]["output"] = ho.tolist()       # swap in a different array...
    b["hardware"]["output_sha256"] = ok_hash    # ...but keep the OLD sealed hash
    write("bundle-gemm-bf16-SWAPPED.json", b)
    fixtures.append(("bundle-gemm-bf16-SWAPPED.json", 4, "swapped array vs sealed hash"))

    # K6 — degraded fast path (systematic bias) -> REPRODUCIBILITY (exit 4)
    b = base_bundle("gemm_bf16_tile1", "bf16", vis, ho)
    b["hardware"]["output"] = (vis + delta).tolist()
    reseal(b["hardware"])                        # rehash so it fails at the DIFF, not the hash
    write("bundle-gemm-bf16-DEGRADED.json", b)
    fixtures.append(("bundle-gemm-bf16-DEGRADED.json", 4, "biased output: passes max-abs, fails zero-mean"))

    # K8 — overfit: good on visible, degraded on the held-out batch -> ANTI-OVERFIT (exit 6)
    b = base_bundle("gemm_bf16_tile1", "bf16", vis, ho)
    b["holdout_hardware"]["output"] = (ho + delta).tolist()
    reseal(b["holdout_hardware"])
    write("bundle-gemm-bf16-INPUTFIT.json", b)
    fixtures.append(("bundle-gemm-bf16-INPUTFIT.json", 6, "accurate on visible inputs, biased on held-out"))

    # K1 (neg) — malformed bundle (missing kernel block) -> SCHEMA (exit 2)
    b = base_bundle("gemm_bf16_tile1", "bf16", vis, ho)
    del b["kernel"]
    write("bundle-gemm-bf16-BADSCHEMA.json", b)
    fixtures.append(("bundle-gemm-bf16-BADSCHEMA.json", 2, "missing kernel block"))

    # ---- int8: exact integer path ----
    ivis = honest_int8_gemm(SHAPE, 2468)
    iho = honest_int8_gemm(SHAPE, 13579)

    # K7 — genuine int8 ACCEPT (bit-exact)
    write("bundle-int8-OK.json", base_bundle("gemm_int8_tile1", "int8", ivis, iho))
    fixtures.append(("bundle-int8-OK.json", 0, "bit-exact int8 kernel"))

    # K7 (neg) — a single 1-lsb tamper -> REPRODUCIBILITY (exit 4), hash resealed
    b = base_bundle("gemm_int8_tile1", "int8", ivis, iho)
    out = [row[:] for row in b["hardware"]["output"]]
    out[0][0] = int(out[0][0]) + 1              # flip one element by one
    b["hardware"]["output"] = out
    reseal(b["hardware"])                        # reseal so it fails at bit-exactness, not the hash
    write("bundle-int8-TAMPER.json", b)
    fixtures.append(("bundle-int8-TAMPER.json", 4, "one int element off by 1 (must be bit-exact)"))

    # ---- self-verify every fixture against the judge ----
    print("Oracle-Diff Gate — fixture self-verification\n")
    ok = True
    for name, want, note in fixtures:
        bundle = json.load(open(os.path.join(HERE, name)))
        try:
            jk.verify(bundle)
            got = 0
        except jk.Reject as r:
            got = r.code
        mark = "ok " if got == want else "FAIL"
        if got != want:
            ok = False
        print(f"  [{mark}] {name:36s} exit {got} (want {want})  — {note}")

    # diagnostic: show the honest vs degraded numeric separation
    mr = float(np.abs(ref_vis).max())
    rtol, atol = jk.derive_tolerance("bf16", SHAPE[2], mr)
    he = vis - ref_vis
    bias_bound = jk.BIAS_C * jk.ULP["bf16"] * float(np.abs(ref_vis).mean())
    print(f"\n  bf16 honest: max|err|={float(np.abs(he).max()):.4g}  mean_bias={float(he.mean()):.4g}  "
          f"(rtol={rtol:.4g}, atol={atol:.4g}, bias_bound={bias_bound:.4g}, delta={delta:.4g})")
    print(f"\n{'ALL FIXTURES OK' if ok else 'FIXTURE MISMATCH — see above'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
